# Generated by Django 3.1.1 on 2020-11-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='Category',
        ),
    ]
