# Generated by Django 3.1.1 on 2020-11-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_auto_20201105_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
